on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ] # add ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: run nox
        run: nox